workflows:
  version: 2
  test:
    jobs:
      - test-3.5
      - test-3.6
      - test-3.7
      - test-3.8
      - test-3.9
      - test-3.10
      - test-latest
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    environment:
      PYTHON_VERSION=3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install python-dev

      - run:
          name: Write Python version to file
          command: |
            echo $PYTHON_VERSION > /tmp/PYTHON_VERSION
            cat /tmp/PYTHON_VERSION

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "/tmp/PYTHON_VERSION" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .[dev]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "/tmp/PYTHON_VERSION" }}

      - run:
          name: Run test suite
          command: |
            . venv/bin/activate
            pytest
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
    environment:
      PYTHON_VERSION=3.5
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
    environment:
      PYTHON_VERSION=3.7
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8
    environment:
      PYTHON_VERSION=3.8
  test-3.9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9
    environment:
      PYTHON_VERSION=3.9
  test-3.10:
    <<: *test-template
    docker:
      - image: circleci/python:3.10
    environment:
      PYTHON_VERSION=3.10
  test-latest:
    <<: *test-template
    docker:
      - image: circleci/python:latest
    environment:
      PYTHON_VERSION=latest
